sets = {
    'Wall Street': ['Wolf of Wall Street, The', 'Wall Street: Money Never Sleeps', 'Wall Street'],
    'Star Wars': ['Star Wars: A New Hope',
                  'Star Wars: The Empire Strikes Back',
                  'Star Wars: Return of the Jedi',
                  'Star Wars: The Phantom Menace',
                  'Star Wars: Attack of the Clones',
                  'Star Wars: Revenge of the Sith',
                  'Star Wars: The Force Awakens'],
    'Star Trek': ['Star Trek: The Motion Picture',
                  'Star Trek II: The Wrath of Khan',
                  'Star Trek: Generations',
                  'Star Trek: First Contact',
                  'Star Trek: Nemesis',
                  'Star Trek'],
    'Analyze This':['Analyze This', 'Analyze That'],
    'Godfather':['Godfather', 'Godfather Part II', 'Godfather Part III'],
    'James Bond':['Goldeneye', 'Tomorrow Never Dies', 'World is not Enough, The'],
    'Ghostbusters':['Ghostbusters', 'Ghostbusters 2'],
    'Indiana Jones':['Indiana Jones and the Raiders of the Lost Ark',
                     'Indiana Jones and the Last Crusade',
                     'Indiana Jones and the Temple of Doom',
                     'Indiana Jones IV'],
    'Lord of the Rings':['Lord of the Rings: Fellowship of the Ring, The',
                         'Lord of the Rings: Return of the King',
                         'Lord of the Rings: The Two Towers'],
    'Harry Potter':['Harry Potter and the Sorcerer\'s Stone',
                    'Harry Potter and the Chamber of Secrets',
                    'Harry Potter and the Prisoner of Azkaban',
                    'Harry Potter and the Goblet of Fire',
                    'Harry Potter and the Half-Blood Prince',
                    'Harry Potter and the Deathly Hallows Part 1',
                    'Harry Potter and the Deathly Hallows Part 2'],
    'Avatar':['Avatar', 'Dances with Wolves', 'Last Samurai, The', 'Pocahontas'],
    'Patriot': ['Patriot, The', 'Postman, The', 'Braveheart', 'Last Samurai, The'],
    'Jason Bourne':['Bourne Identity, The', 'Bourne Supremacy, The', 'Bourne Ultimatum, The'],
    'Dystopia':['Postman, The', 'Book of Eli, The', 'Blade Runner', 'Gattaca', 'Oblivion', 'Fifth Element, The'],
    }